apiVersion: blueprints.cloud.google.com/v1alpha1
kind: ProjectServiceSet
metadata:
  name: guardrails-bootstrap-services # kpt-set: ${project-id}-services
  namespace: config-control # kpt-set: ${project-namespace}
  annotations:
    cnrm.cloud.google.com/deletion-policy: "false"
    config.kubernetes.io/local-config: "true"
    cnrm.cloud.google.com/disable-dependent-services: "false"
spec:
  services: # list of services to generate
    - compute.googleapis.com
    - bigquery.googleapis.com
    - pubsub.googleapis.com
    - container.googleapis.com
    - binaryauthorization.googleapis.com
    - artifactregistry.googleapis.com
    - anthos.googleapis.com
    - anthosconfigmanagement.googleapis.com
    - mesh.googleapis.com
    - sourcerepo.googleapis.com
    - gkehub.googleapis.com
    - multiclusteringress.googleapis.com
    - multiclusterservicediscovery.googleapis.com
  projectID: guardrails-bootstrap # kpt-set: ${project-id}
